# Generado automaticamente - NO editar manualmente
# Fuente: shared/docs/Rutas_de_logs.xlsx
---
log_config:
  servicio: WEBLOGIC_PDN
  become_user: oracle
  become_group: oinstall
  log_paths:
    - paths:
        - /u01/app/oracle/admin/12.2.1/DinamicaIPS_Pdn_Domain/servers/WLS_MSGDINP02/logs
      patterns:
        - '*.out*'
        - '*.log*'
