# Generado automaticamente - NO editar manualmente
# Fuente: shared/docs/Rutas_de_logs.xlsx
---
log_config:
  servicio: NO_WEBLOGIC_LABO
  become_user: apache
  become_group: apache
  log_paths:
    - paths:
        - /opt/app/utils/httpd/httpd/logs/labwww.epssura.com
      patterns:
        - '*_log*'
