# Generado automaticamente - NO editar manualmente
# Fuente: shared/docs/Rutas_de_logs.xlsx
---
log_config:
  servicio: WEBLOGIC_LAB
  become_user: oracle
  become_group: oinstall
  log_paths:
    - paths:
        - /u01/app/oracle/admin/domains/SURA_Func_Lab_Domain1/SGADMOLDAPPL01/aserver/SURA_Func_Lab_Domain1/servers/AdminServer/logs
        - /u01/app/oracle/admin/domains/Cotizador_Lab_Domain/SGADMOLDAPPL01/aserver/Cotizador_Lab_Domain/servers/AdminServer/logs
      patterns:
        - '*.log*'
