# Generado automaticamente - NO editar manualmente
# Fuente: shared/docs/Rutas_de_logs.xlsx
---
log_config:
  servicio: WEBLOGIC_PDN
  become_user: oracle
  become_group: oinstall
  log_paths:
    - paths:
        - /u01/app/oracle/admin/domains/COTIZADOR_PDN_Domain/SGADMOLDAPPP01/mserver/COTIZADOR_PDN_Domain/servers
        - /u01/app/oracle/admin/domains/SURA_Func_PDN_Domain1/SGADMOLDAPPP01/mserver/SURA_Func_PDN_Domain1/servers
      patterns:
        - '*.log*'
        - '*.out*'
