# Generado automaticamente - NO editar manualmente
# Fuente: shared/docs/Rutas_de_logs.xlsx
---
log_config:
  servicio: WEBLOGIC_DLLO
  become_user: oracle
  become_group: oinstall
  log_paths:
    - paths:
        - /u01/app/oracle/admin/domains/SURA_FUNCIONAL1/servers
      patterns:
        - '*.out*'
